### ISSUE TITLE
ente always running

### ISSUE THREAD

**Issue by ThreaT** [ente-io/photos-desktop#257]
**Describe the bug**
ente always runs, always consumes resources, even when closed

**To Reproduce**
1. Close ente desktop app
2. open task manager on windows
3. search "ente"

**Expected behavior**
Should not appear in task manager but does

**Screenshots**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by vishnukvmd** [comment]
Hey, this is intentional. There are features like [Watch folders](https://ente.io/faq/features/watch-folders/) and [Continuous exports](https://ente.io/blog/export-got-wings/#continous-sync) that require the app to run in the background.

You can kill the app by right-clicking on it from the status bar, and closing it.

I'm closing this for now, but feel free to reopen if we've misunderstood the issue!
